name: xsoulspace_foundation
description: Shared utils, extensions, and helpers.
version: 0.0.2
homepage: https://github.com/xsoulspace/life_hooks/packages/xsoulspace_foundation
environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  shared_preferences: ^2.3.2
  uuid: ^4.5.1
dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  xsoulspace_lints: ^0.0.11
